sarcastic_jokes = [
    "Oh, you're really good at pointing out the obvious. What's your superpower?",
    "Sarcasm is just one more service we offer.",
    "Please, if we wanted your opinion, we would have asked for it... a long time ago.",
    "I'm not saying I hate you, but I would unplug your life support to charge my phone.",
    "Wow, you have a lot of well-wishers. They would all like to throw you down one.",
    "Of course I talk to myself. Sometimes I need expert advice.",
    "Sarcasm: Because beating the crap out of people is illegal.",
    "If I throw a stick, will you leave?",
    "You're not stupid; you just have bad luck thinking.",
    "I'd agree with you but then we'd both be wrong.",
    "Oh, I'm sorry, did the middle of my sentence interrupt the beginning of yours?",
    "I'm not saying you're old, but if you were a movie, it would be in black and white.",
    "I'm not a gynecologist, but I'll take a look.",
    "I'd insult you, but then the garbage would get mad.",
    "I'm trying to see things from your perspective, but I can't get my head that far up my rear end.",
    "I'm not arguing; I'm just explaining why I'm right.",
]

diverse_jokes = [
    "I'm on a seafood diet. I see food and I eat it. It's that simple!",
    "Why don't oysters donate to charity? Because they are shellfish!",
    "I used to be a baker, but I couldn't make enough dough. So, I became a banker instead!",
    "Why did the scarecrow become a successful motivational speaker? Because he was outstanding in his field!",
    "Why don't scientists trust atoms? Because they make up everything, but who can blame them for their little atomic egos?",
    "I'm reading a book on anti-gravity. It's impossible to put down, and trust me, I've tried!",
    "I told my wife she was drawing her eyebrows too high. She looked surprised, to say the least!",
    "Why was the math book sad? Because it had too many problems to solve, and no one was listening to its solutions!",
    "I used to play piano by ear, but now I use my hands. It's a lot more practical that way!",
    "What did one wall say to the other wall? I'll meet you at the corner!",
    "I'm friends with all electricians. We have such good current connections!",
    "Why don't skeletons fight each other? Because they don't have the guts. They're all bones and no action!",
    "What did the janitor say when he jumped out of the closet? Supplies!",
    "Why did the bicycle fall over? Because it was two-tired and couldn't handle the pressure!",
    "Why did the tomato turn red? Because it saw the salad dressing!",
]

funny_jokes = [
    "Why don't scientists trust atoms? Because they make up everything!",
    "Parallel lines have so much in common. It's a shame they'll never meet.",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "Why did the scarecrow win an award? Because he was outstanding in his field.",
    "I used to play piano by ear, but now I use my hands.",
    "I'm reading a book on anti-gravity. It's impossible to put down.",
    "Did you hear about the mathematician who's afraid of negative numbers? He'll stop at nothing to avoid them.",
    "I told my wife she was only drawing her eyebrows too high. She looked surprised.",
    "I'm on a seafood diet. I see food and I eat it.",
    "What did the grape say when it got stepped on? Nothing, it just let out a little whine.",
    "I used to be a baker, but I couldn't make enough dough.",
    "What do you call a bear with no teeth? A gummy bear.",
    "Why don't skeletons fight each other? They don't have the guts.",
    "I'm friends with all electricians. We have such good current connections.",
    "Why did the bicycle fall over? Because it was two-tired!",
]